title: "SV1TFB"
name: "Frank Fourlas"
email: "frank.fourlas@gmail.com"
description: >-
  This website contains information about my self, my work
  and, most importantly, my hobbies. Enjoy!
baseurl: "" 
domain: "sv1tfb.gr"
url: "https://sv1tfb.gr"
# twitter_username: jekyllrb
github_username: frank20a
minimal_mistakes_skin: dark

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jemoji
  - jekyll-gist
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-stickyposts
  
whitelist:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jemoji
  - jekyll-gist
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-stickyposts

include:
  - _pages

# Pagination
paginate: 5
paginate_path: /page/:num/

# Theme settings
locale: "en"
title_separator: "-"
subtitle: "The projects of Frank Fourlas"
repository: "frank20a/frank20a.github.io"
teaser: "/assets/images/default-teaser.png"
og_image: /assets/images/default-teaser.png
logo: "/assets/images/logo.png"
masthead_title: "SV1TFB - Frank's Projects"
date_format: "%d/%m/%Y"
enable_copy_code_button: true
comments:
  provider: "utterances"
  utterances:
    theme: "github-dark"
    issue_term: "pathname"
    label: "comment"
atom_feed:
  hide: true
search: true
social:
  type: Person
  name: Fragiskos Fourlas
  links:
    - "https://scholar.google.com/citations?user=4E7YLMgAAAAJ&hl=en"
    - "https://www.linkedin.com/in/f-fourlas/"
    - "https://people.utwente.nl/f.fourlas"
author: Frank Fourlas
timezone: Europe/Amsterdam
breadcrumbs: true
breadcrumb_home_label : "Home"
breadcrumb_separator  : "/"
head_scripts:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      author_profile: true
      comments: true
      share: false
      related: true
      show_date: true
  - scope:
      path: "_posts/project-euler"
      type: posts
    values:
      header:
        image: "/assets/images/pe-teaser.jpg"
        teaser: "/assets/images/pe-teaser.jpg"
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "nav"
  - scope:
      path: ""
      type: tag
    values:
      author_profile: false
      sidebar:
        nav: "nav"
  - scope:
      path: ""
      type: category
    values:
      author_profile: false
      sidebar:
        nav: "nav"

# Archives
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Sticky posts
stickyposts:
  debug: false
  sort: "date"      # Optional sort field; default: "date", use "none" to avoid sorting
  # reverse: false     # Ascending order, default: false
  # retain: false      # Also show sticky posts in their original positions; default: false
  # reverse_sticky: false    # Reverse the order of the sticky posts, e.g. oldest first; default: false
